# Generated by Django 6.0.5 on 2026-05-30 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaGenerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('gestion', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('nombre_plantilla', models.CharField(max_length=200)),
                ('resultado', models.CharField(max_length=50)),
                ('respuesta', models.TextField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
