# Generated by Django 6.0.5 on 2026-06-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillagenerada',
            name='distribuidor',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
