# Generated by Django 6.0.5 on 2026-06-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0002_plantillagenerada_distribuidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillagenerada',
            name='distribuidor',
            field=models.CharField(default='SIN DISTRIBUIDOR', max_length=200),
        ),
    ]
