# Generated by Django 6.0.5 on 2026-07-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_perfil_fondo_alter_perfil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='color',
            field=models.CharField(default='azul', max_length=20),
        ),
    ]
