# Generated by Django 6.0.5 on 2026-07-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_perfil_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='color_personalizado',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
