# Generated by Django 6.0.5 on 2026-07-01 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_perfil_color_personalizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='color',
            new_name='tema',
        ),
    ]
