# Generated by Django 6.0.5 on 2026-07-01 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_color_perfil_tema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='tema',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='color_personalizado',
        ),
    ]
