# Generated by Django 5.2.6 on 2026-07-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_perfil_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='foto',
        ),
        migrations.AddField(
            model_name='perfil',
            name='fondo',
            field=models.ImageField(blank=True, null=True, upload_to='fondos/'),
        ),
    ]
